insert into ayuda (codigo_ayuda, descripcion) values ('AY1', 'silla de ruedas');
insert into ayuda (codigo_ayuda, descripcion) values ('AY2', 'muletas');
insert into ayuda (codigo_ayuda, descripcion) values ('AY3', 'protesis pierna izda');
insert into ayuda (codigo_ayuda, descripcion) values ('AY4', 'protesis pierna dcha');
insert into ayuda (codigo_ayuda, descripcion) values ('AY5', 'protesis brazo izdo');
insert into ayuda (codigo_ayuda, descripcion) values ('AY6', 'protesis brazo dcho');
insert into ayuda (codigo_ayuda, descripcion) values ('AY7', 'protesis mano izda');
insert into ayuda (codigo_ayuda, descripcion) values ('AY8', 'protesis mano dcha');
insert into ayuda (codigo_ayuda, descripcion) values ('AY9', 'protesis pie izdo');
insert into ayuda (codigo_ayuda, descripcion) values ('AY10', 'protesis pie dcho');
insert into ayuda (codigo_ayuda, descripcion) values ('AY11', 'gafas');
insert into ayuda (codigo_ayuda, descripcion) values ('AY12', 'audifono');
